---
# 编译并发布到内网VCS
#
- hosts: compiler
  vars:
       op_user: builder
       source_svn_user: ""
       source_svn_password: ""
       source_repos: http://10.1.0.8/repos/ares/trunk
       source_dir: /home/builder/ZS_BUILD
       compile_script: ./rebuild.sh           # 使用游戏相关的编译脚本
       bin_src_dir: /home/builder/ZS_BUILD/bin/server

       repos_url: http://10.1.0.20/repos/release/wyft
       release_dir: /home/builder/wyft
       svn_user: ""
       svn_password: ""
       db_host: 10.1.0.33
       db_name: ares_clunicode
       db_user: viivgame
       db_password: viivgame
  roles:
     - compiler
