---
# 部署产品
#
- hosts: database
  vars:
       data_dir: /var/lib/mysql       
       master_server_id: 2
       db_name: wyft
       db_init_file: "" # 初始化SQL文件 initial_data_file.sql
       new_db_username: viivgame
       new_db_password: viivgame
       allow_host: 10.1.%.%
  roles:
     - common
     - database
     - datamaster

- hosts: production
  vars:
       repos: http://10.1.0.20/repos/release/wyft/trunk/server
       dest_dir: /home/server/wyft
       svn_user: ""
       svn_password: ""
       op_user: "server"
       xml_cfg_file: 650770c6-1c7d-45f2-9717-f90ef4378262.xml # 需要编辑配置文件
  roles:
    - common
    - production
    - setup
