---
# install mod_dav_svn
#
- name: install mod_dav_svn
  yum: name=mod_dav_svn state=present

# configure mod_dav_svn
- name: configure mod_dav_svn
  copy: src=subversion.conf dest=/etc/httpd/conf.d/subversion.conf.example
  notify:
    - restart httpd
