---
# 安装Apache Httpd服务器
#
- name: Install nginx
  yum: name=nginx state=present

- name: Configure nginx
  template: src=nginx-default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
  - restart nginx

- name: Start nginx service
  service: name=nginx state=started enabled=yes

# Configure Iptables
- name: configure iptables
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp={{ httpd_listen_port }} insertafter="-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT" line="-A INPUT -p tcp  --dport {{ httpd_listen_port}} -j  ACCEPT"
  #ufw: rule=allow proto=tcp port={{ httpd_listen_port }}
  notify:
  - restart iptables
