---
# openssh
#
- name: Upgrade openssh
  yum: name=openssh state=latest

- name: Update openssh config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config mode=0600 owner=root
  notify:
  - restart sshd
