---
# install supervisor
#
- name: install supervisor
  command: pip install supervisor

# configure supervisor
- name: create supervisor configure directory
  file: path=/etc/supervisord.d state=directory

# configure supervisor
- name: configure supervisor
  copy: src=supervisord.conf dest=/etc/supervisord.conf

# start supervisord
#- name: start supervisord
#  command: /usr/bin/supervisord
